-- Cascadia License Check - Seed Verification Sources
-- This migration populates the verification_sources table with all 50 states

-- ============================================================================
-- BOARD OF NURSING (BON) SOURCES
-- ============================================================================
INSERT INTO verification_sources (state, source_type, display_name, lookup_url, instructions, active) VALUES
('AL', 'bon', 'Alabama Board of Nursing', 'https://www.abn.alabama.gov/verify/', 'Search by license number or name. Click on the license to view details.', true),
('AK', 'bon', 'Alaska Board of Nursing', 'https://www.commerce.alaska.gov/cbp/main/search/professional', 'Select "Nursing" as the profession, enter license number or name.', true),
('AZ', 'bon', 'Arizona State Board of Nursing', 'https://azbn.gov/licenses-and-certifications/verification', 'Use the license verification portal to search by license number.', true),
('AR', 'bon', 'Arkansas State Board of Nursing', 'https://www.arsbn.org/license-verification', 'Enter license number or search by name.', true),
('CA', 'bon', 'California Board of Registered Nursing', 'https://www.rn.ca.gov/verification.shtml', 'Use License Verification link and enter license number.', true),
('CO', 'bon', 'Colorado State Board of Nursing', 'https://apps.colorado.gov/dora/licensing/Lookup/LicenseLookup.aspx', 'Select profession and enter license information.', true),
('CT', 'bon', 'Connecticut Board of Examiners for Nursing', 'https://www.elicense.ct.gov/Lookup/LicenseLookup.aspx', 'Select license type and search by number or name.', true),
('DE', 'bon', 'Delaware Board of Nursing', 'https://dpr.delaware.gov/boards/nursing/', 'Click Verify a License and search.', true),
('FL', 'bon', 'Florida Board of Nursing', 'https://mqa-internet.doh.state.fl.us/MQASearchServices/Home', 'Search by license number or name.', true),
('GA', 'bon', 'Georgia Board of Nursing', 'https://sos.ga.gov/PLB/pls/plb_public_qry.verify_lic', 'Enter license number to verify status.', true),
('HI', 'bon', 'Hawaii Board of Nursing', 'https://cca.hawaii.gov/pvl/boards/nursing/', 'Use online verification system.', true),
('ID', 'bon', 'Idaho Board of Nursing', 'https://ibn.idaho.gov/IBNPortal/LicenseVerification.aspx', 'Search by license number or name.', true),
('IL', 'bon', 'Illinois Board of Nursing', 'https://online-dfpr.micropact.com/lookup/licenselookup.aspx', 'Select license type and enter information.', true),
('IN', 'bon', 'Indiana State Board of Nursing', 'https://mylicense.in.gov/EVerification/', 'Search by license number or name.', true),
('IA', 'bon', 'Iowa Board of Nursing', 'https://eservices.iowa.gov/PublicPortal/Iowa/IBON/licensequery/SearchPage.jsp', 'Enter license number or search by name.', true),
('KS', 'bon', 'Kansas State Board of Nursing', 'https://www.kansas.gov/ssrv-ksbn/', 'Use license verification search.', true),
('KY', 'bon', 'Kentucky Board of Nursing', 'https://kbn.ky.gov/NR/exeres/2C48BCD6-E1F8-4F00-B1D1-5A3C6C1E1BD5.htm', 'Click License Verification and search.', true),
('LA', 'bon', 'Louisiana State Board of Nursing', 'https://www.lsbn.state.la.us/Licensure-Verification', 'Use online verification portal.', true),
('ME', 'bon', 'Maine State Board of Nursing', 'https://www.pfr.maine.gov/almsonline/almsquery/SearchIndividual.aspx', 'Search by license number or name.', true),
('MD', 'bon', 'Maryland Board of Nursing', 'https://mbon.maryland.gov/Pages/verify-a-license.aspx', 'Use license lookup tool.', true),
('MA', 'bon', 'Massachusetts Board of Registration in Nursing', 'https://checkalicense.hhs.state.ma.us/', 'Search by license number or name.', true),
('MI', 'bon', 'Michigan Board of Nursing', 'https://w2.lara.state.mi.us/VAL/License/Search', 'Enter license information to verify.', true),
('MN', 'bon', 'Minnesota Board of Nursing', 'https://mn.gov/boards/nursing/public/license-verification/', 'Use license verification search.', true),
('MS', 'bon', 'Mississippi Board of Nursing', 'https://gateway.mississippi.gov/LicenseVerification/', 'Search by license number.', true),
('MO', 'bon', 'Missouri State Board of Nursing', 'https://pr.mo.gov/licensee-search.asp', 'Select Nursing and search.', true),
('MT', 'bon', 'Montana Board of Nursing', 'https://ebiz.mt.gov/publicportal/mt/dlibsdlv/licenseesearch.aspx', 'Search by license number or name.', true),
('NE', 'bon', 'Nebraska Board of Nursing', 'https://www.nebraska.gov/LISSearch/search.cgi', 'Select license type and search.', true),
('NV', 'bon', 'Nevada State Board of Nursing', 'https://nevadanursingboard.org/license-verification/', 'Use online license verification.', true),
('NH', 'bon', 'New Hampshire Board of Nursing', 'https://nhlicenses.nh.gov/', 'Search by license number or name.', true),
('NJ', 'bon', 'New Jersey Board of Nursing', 'https://newjersey.mylicense.com/verification/', 'Enter license information.', true),
('NM', 'bon', 'New Mexico Board of Nursing', 'https://www.rld.nm.gov/boards-commissions/individual-boards-a-m/board-of-nursing/', 'Click License Verification.', true),
('NY', 'bon', 'New York State Education Department', 'http://www.op.nysed.gov/opsearches.htm', 'Search by license number or name.', true),
('NC', 'bon', 'North Carolina Board of Nursing', 'https://portal.ncbon.com/LicenseVerification/', 'Enter license number to verify.', true),
('ND', 'bon', 'North Dakota Board of Nursing', 'https://www.ndbon.org/', 'Use License Lookup tool.', true),
('OH', 'bon', 'Ohio Board of Nursing', 'https://elicense.ohio.gov/oh_licenselookup', 'Search by license number or name.', true),
('OK', 'bon', 'Oklahoma Board of Nursing', 'https://www.ok.gov/nursing/verify.html', 'Use license verification search.', true),
('OR', 'bon', 'Oregon State Board of Nursing', 'https://osbn.oregon.gov/OSBNVerification/', 'Enter license information.', true),
('PA', 'bon', 'Pennsylvania State Board of Nursing', 'https://www.pals.pa.gov/#!/page/search', 'Search by license number.', true),
('RI', 'bon', 'Rhode Island Board of Nurse Registration', 'https://health.ri.gov/find/licensees/', 'Search nursing licenses.', true),
('SC', 'bon', 'South Carolina Board of Nursing', 'https://verify.llronline.com/LicLookup/Nurse/', 'Enter license number or name.', true),
('SD', 'bon', 'South Dakota Board of Nursing', 'https://nursing.sd.gov/', 'Use License Lookup.', true),
('TN', 'bon', 'Tennessee Board of Nursing', 'https://apps.health.tn.gov/licensure/', 'Search by license number or name.', true),
('TX', 'bon', 'Texas Board of Nursing', 'https://www.bon.texas.gov/forms/verification.asp', 'Enter license number to verify.', true),
('UT', 'bon', 'Utah Board of Nursing', 'https://www.dopl.utah.gov/licensing/index.html', 'Use license lookup tool.', true),
('VT', 'bon', 'Vermont Board of Nursing', 'https://secure.professionals.vermont.gov/prweb/PRServlet', 'Search professional licenses.', true),
('VA', 'bon', 'Virginia Board of Nursing', 'https://dhp.virginiainteractive.org/Lookup/Index', 'Search by license number.', true),
('WA', 'bon', 'Washington State Nursing Commission', 'https://fortress.wa.gov/doh/providercredentialsearch/', 'Enter credential information.', true),
('WV', 'bon', 'West Virginia Board of Examiners for RNs', 'https://wvrnboard.wv.gov/licensing/Pages/license-verification.aspx', 'Verify license status.', true),
('WI', 'bon', 'Wisconsin Board of Nursing', 'https://licensesearch.wi.gov/', 'Search by license number or name.', true),
('WY', 'bon', 'Wyoming State Board of Nursing', 'https://nursing-online.state.wy.us/Home/VerifyLicense', 'Enter license number.', true),
('DC', 'bon', 'District of Columbia Board of Nursing', 'https://doh.dc.gov/service/verify-a-health-professional-license', 'Search health professional licenses.', true);

-- ============================================================================
-- CNA REGISTRY SOURCES (for states with separate registries)
-- ============================================================================
INSERT INTO verification_sources (state, source_type, display_name, lookup_url, instructions, active) VALUES
('AL', 'cna_registry', 'Alabama CNA Registry', 'https://www.abn.alabama.gov/verify/', 'CNA verification through BON portal.', true),
('AK', 'cna_registry', 'Alaska CNA Registry', 'https://www.commerce.alaska.gov/cbp/main/search/professional', 'Search for Nurse Aide certification.', true),
('AZ', 'cna_registry', 'Arizona CNA Registry', 'https://www.azhealth.gov/CNARegistry/', 'Search the Nurse Aide Registry.', true),
('AR', 'cna_registry', 'Arkansas CNA Registry', 'https://www.healthy.arkansas.gov/programs-services/topics/nurse-aide-registry', 'Access Nurse Aide Registry.', true),
('CA', 'cna_registry', 'California Nurse Aide Registry', 'https://www.cdph.ca.gov/Programs/CHCQ/LCP/Pages/NurseAideRegistry.aspx', 'Verify CNA certification status.', true),
('CO', 'cna_registry', 'Colorado Nurse Aide Registry', 'https://apps.colorado.gov/dora/licensing/Lookup/LicenseLookup.aspx', 'Select Nursing Home Administrator / Nurse Aide.', true),
('CT', 'cna_registry', 'Connecticut Nurse Aide Registry', 'https://www.ct.gov/dph/cwp/view.asp?a=3121&q=400706', 'Search the NAR database.', true),
('DE', 'cna_registry', 'Delaware CNA Registry', 'https://dhss.delaware.gov/dhss/dltcrp/cnalisting.html', 'Access CNA Registry.', true),
('FL', 'cna_registry', 'Florida CNA Registry', 'https://appsmqa.doh.state.fl.us/mqa/', 'Search CNA certification.', true),
('GA', 'cna_registry', 'Georgia Nurse Aide Registry', 'https://mmis.georgia.gov/nar/', 'Verify nurse aide status.', true),
('HI', 'cna_registry', 'Hawaii CNA Registry', 'https://health.hawaii.gov/ohca/medicare-702/', 'Contact OHCA for verification.', true),
('ID', 'cna_registry', 'Idaho CNA Registry', 'https://healthandwelfare.idaho.gov/providers/nursing-home-licenses/nurse-aide-registry', 'Access Nurse Aide Registry.', true),
('IL', 'cna_registry', 'Illinois Health Care Worker Registry', 'https://hcwr.ilsos.net/', 'Search Health Care Worker Registry.', true),
('IN', 'cna_registry', 'Indiana Nurse Aide Registry', 'https://www.in.gov/isdh/24799.htm', 'Verify CNA status.', true),
('IA', 'cna_registry', 'Iowa Direct Care Worker Registry', 'https://dia-hfd.iowa.gov/DIA_HFD/Home.do', 'Search registry.', true),
('KS', 'cna_registry', 'Kansas Nurse Aide Registry', 'https://www.kdads.ks.gov/commissions/survey-certification-and-credentialing-commission/nurse-aide-registry', 'Access registry online.', true),
('KY', 'cna_registry', 'Kentucky Nurse Aide Registry', 'https://chfs.ky.gov/agencies/ohda/Pages/nar.aspx', 'Search NAR database.', true),
('LA', 'cna_registry', 'Louisiana CNA Registry', 'https://www.lsbn.state.la.us/', 'Verify through LSBN.', true),
('ME', 'cna_registry', 'Maine CNA Registry', 'https://www.maine.gov/dhhs/mecdc/dlrs/cna-registry/', 'Access registry.', true),
('MD', 'cna_registry', 'Maryland Nurse Aide Registry', 'https://mbon.maryland.gov/Pages/cna.aspx', 'Search CNA registry.', true),
('MA', 'cna_registry', 'Massachusetts Nurse Aide Registry', 'https://www.mass.gov/lists/nurse-aide-registry', 'Verify certification.', true),
('MI', 'cna_registry', 'Michigan Nurse Aide Registry', 'https://www.michigan.gov/lara/bureau-list/bhs/health-systems-section/nurse-aide-registry', 'Access registry.', true),
('MN', 'cna_registry', 'Minnesota Nursing Assistant Registry', 'https://www.health.state.mn.us/facilities/regulation/nar/', 'Search registry.', true),
('MS', 'cna_registry', 'Mississippi Nurse Aide Registry', 'https://msdh.ms.gov/msdhsite/_static/30,0,166.html', 'Verify nurse aide.', true),
('MO', 'cna_registry', 'Missouri Nurse Aide Registry', 'https://health.mo.gov/safety/cnaregistry/', 'Search registry.', true),
('MT', 'cna_registry', 'Montana CNA Registry', 'https://dphhs.mt.gov/qad/licensure-certification/CNA', 'Access registry.', true),
('NE', 'cna_registry', 'Nebraska Nurse Aide Registry', 'https://dhhs.ne.gov/licensure/pages/nurse-aide-registry.aspx', 'Verify status.', true),
('NV', 'cna_registry', 'Nevada CNA Registry', 'https://nvnursingboard.org/cnas/', 'Search CNA registry.', true),
('NH', 'cna_registry', 'New Hampshire Nurse Aide Registry', 'https://www.dhhs.nh.gov/ombp/red/', 'Access registry.', true),
('NJ', 'cna_registry', 'New Jersey Nurse Aide Registry', 'https://www.nj.gov/health/healthfacilities/nar/', 'Verify certification.', true),
('NM', 'cna_registry', 'New Mexico CNA Registry', 'https://www.nmhealth.org/about/ddsd/pgsv/nar/', 'Search registry.', true),
('NY', 'cna_registry', 'New York Nurse Aide Registry', 'https://www.health.ny.gov/professionals/nursing_home_administrator/nurse_aide_registry.htm', 'Access NAR.', true),
('NC', 'cna_registry', 'North Carolina Nurse Aide Registry', 'https://www.ncnar.org/', 'Search registry.', true),
('ND', 'cna_registry', 'North Dakota Nurse Aide Registry', 'https://www.health.nd.gov/providers/nurse-aide-registry', 'Verify status.', true),
('OH', 'cna_registry', 'Ohio Nurse Aide Registry', 'https://odh.ohio.gov/know-our-programs/nurse-aide-registry/', 'Search registry.', true),
('OK', 'cna_registry', 'Oklahoma Nurse Aide Registry', 'https://oklahoma.gov/health/health-education/protective-health-services/nurse-aide-registry.html', 'Access registry.', true),
('OR', 'cna_registry', 'Oregon CNA Registry', 'https://www.osbn.state.or.us/', 'Verify through OSBN.', true),
('PA', 'cna_registry', 'Pennsylvania Nurse Aide Registry', 'https://www.health.pa.gov/topics/facilities/nursing%20homes/Pages/Nurse-Aide-Registry.aspx', 'Search registry.', true),
('RI', 'cna_registry', 'Rhode Island CNA Registry', 'https://health.ri.gov/healthrisks/nurseaide/', 'Access registry.', true),
('SC', 'cna_registry', 'South Carolina Nurse Aide Registry', 'https://www.scdhec.gov/health/health-facility-regulations/healthcare-facilities-licensing/nurse-aide-registry', 'Search registry.', true),
('SD', 'cna_registry', 'South Dakota Nurse Aide Registry', 'https://doh.sd.gov/providers/licensure/Certified-Nurse-Aide/', 'Verify status.', true),
('TN', 'cna_registry', 'Tennessee Nurse Aide Registry', 'https://www.tn.gov/health/health-program-areas/health-professional-boards/nar-board.html', 'Search registry.', true),
('TX', 'cna_registry', 'Texas Nurse Aide Registry', 'https://www.hhs.texas.gov/providers/long-term-care-providers/nursing-facilities/nurse-aide-registry', 'Access registry.', true),
('UT', 'cna_registry', 'Utah Nurse Aide Registry', 'https://unar.utah.gov/', 'Verify certification.', true),
('VT', 'cna_registry', 'Vermont Nurse Aide Registry', 'https://www.sec.state.vt.us/professional-regulation/profession/nurse-aide.aspx', 'Search registry.', true),
('VA', 'cna_registry', 'Virginia Nurse Aide Registry', 'https://www.vdh.virginia.gov/licensure-and-certification/nar/', 'Access registry.', true),
('WA', 'cna_registry', 'Washington Nursing Assistant Registry', 'https://fortress.wa.gov/doh/providercredentialsearch/', 'Search credentials.', true),
('WV', 'cna_registry', 'West Virginia Nurse Aide Registry', 'https://ohflac.wv.gov/nurse-aide-program/', 'Access registry.', true),
('WI', 'cna_registry', 'Wisconsin Nurse Aide Registry', 'https://www.dhs.wisconsin.gov/caregiver/nurse-aide-registry.htm', 'Search registry.', true),
('WY', 'cna_registry', 'Wyoming CNA Registry', 'https://health.wyo.gov/aging/hls/certificationlicensure/cna-registry/', 'Verify status.', true),
('DC', 'cna_registry', 'DC Nurse Aide Registry', 'https://doh.dc.gov/service/nurse-aide-registry', 'Search registry.', true);

-- ============================================================================
-- NURSYS E-NOTIFY SOURCE
-- ============================================================================
INSERT INTO verification_sources (state, source_type, display_name, lookup_url, instructions, supports_api, active) VALUES
(NULL, 'nursys', 'Nursys e-Notify', 'https://www.nursys.com/eNLC/eNLCSearch.aspx', 'Automated notifications for enrolled licenses via e-Notify API.', true, true);
